### ISSUE TITLE
Persist Installation directory /opt

### ISSUE THREAD

**Issue by philippkayser** [cptactionhank/docker-atlassian-jira-service-desk#12]
Is there any solution to persist /opt/atlassian/jira directory?

We want to mount it like /var/atlassian/jira to /opt/directory/jira-opt . & ../jira-var

May there is any issue with permissions on it? For /var the user-id inside the container works fine.

```
version: '2'

services:
  db:
    container_name: jira-servicedesk_prod_db
    image: postgres
    networks:
      - servicedesk
    volumes:
      - /opt/docker/04-jira-servicedesk/db:/var/lib/postgresql/data
    ports:
     - "5432"
    environment:
     - POSTGRES_USER=jiraservicedesk
     - POSTGRES_PASSWORD=password
     - POSTGRES_DB=jiraservicedeskdb
  desk:
    container_name: jira-servicedesk_prod_desk
    image: cptactionhank/atlassian-jira-service-desk:latest
    depends_on:
      - db
    networks:
      - web
      - servicedesk
    volumes:
      - /opt/docker/04-jira-servicedesk/servicedesk/HOME:/var/atlassian/jira
      - /opt/docker/04-jira-servicedesk/servicedesk/OPT:/opt/atlassian/jira
    environment:
      - CATALINA_OPTS=-Xms786m -Xmx1g
    labels:
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:servicedesk.domain.com"
      - "traefik.port=8080"
    ports:
      - "8080"

networks:
  web:
     external: true
  servicedesk:
```
